[install]
cmds = [
  "mkdir -p /var/log/nginx /var/run/nginx",
  "composer install --no-interaction --prefer-dist --ignore-platform-reqs"
]

[build]
cmds = [
  "php -d memory_limit=-1 artisan optimize --no-interaction || true",
  "php -d memory_limit=-1 artisan config:cache --no-interaction || true"
]

[start]
cmd = "vendor/bin/heroku-php-apache2 public/"
